url: https://mathswithtina.github.io/
baseurl:

# Site settings
title: Maths Courses
email: mathswithtina@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
#- name: Tina Mgeladze
#  pic: 1
#  position: Lead Designer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

- name: Tina Mgeladze
  pic: 2
  position: მე ვარ თინა მგელაძე, მათემატიკის მასწავლებელი თბილისიდან. მაქვს მოსწავლეებთან მუშაობის 13 წლიანი წარმატებული სამუშაო გამოცდილება.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

#- name: Diana Petersen
#  pic: 3
#  position: Lead Developer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/mathswithtina?igsh=OGQ5ZDc2ODk2ZA==
  - title: facebook
    url: https://www.facebook.com/tikuna.mgeladze.5?mibextid=2JQ9oc
  - title: linkedin
    url: https://www.linkedin.com/in/tina-mgeladze-2baa28219

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
